### ISSUE TITLE
About the bug of function is_compute_kernel in HolisticTraceAnalysis/hta/utils /utils.py

### ISSUE THREAD

**Issue by zwj0117** [facebookresearch/HolisticTraceAnalysis#220]
### 🐛 Describe the bug

NCCL_COMPUTE_KERNEL_RE = re.compile(r"(^nccl.*Kernel)|(.*(Memcpy)|(Memset))|(.*Sync)")

def is_compute_kernel(name: str) -> bool:
    """
    Check if a given GPU kernel is a computation kernel.
    Args:
        name (str): name of the GPU kernel.
    Returns:
        A boolean indicating if the kernel is a computation kernel.
    """
    return not NCCL_COMPUTE_KERNEL_RE.match(name)

eg：cudaMemsetsync will be considered as the  compute kernel

### Steps to reproduce

NCCL_COMPUTE_KERNEL_RE = re.compile(r"(^nccl.*Kernel)|(.*(Memcpy)|(Memset))|(.*Sync)")

### Expected behavior

NCCL_COMPUTE_KERNEL_RE = re.compile(r"(^nccl.*Kernel)|(.*(Memcpy)|(.*Memset))|(.*Sync)")

### Environment

master

**Comment by rena-ertam028** [comment]
AI tried to solve the issue:

Modified the regular expression pattern for NCCL_COMPUTE_KERNEL_RE to properly handle Memset operations. The old pattern incorrectly treated cudaMemsetsync as a compute kernel. The new pattern ensures that any kernel name containing 'Memset' (whether in the middle or at the start) is not considered a compute kernel.

You can review changes in this commit: https://github.com/rena-ertam028/facebookresearch-HolisticTraceAnalysis-220/commit/4c626eb463e1166072fe44ce527b61087084d7a8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by zwj0117** [comment]
NCCL_COMPUTE_KERNEL_RE = re.compile(r"(^nccl.*Kernel)|(.*(Memcpy)|(Memset))|(.*Sync)")


def is_compute_kernel(name: str) -> bool:
    """
    Check if a given GPU kernel is a computation kernel.
    Args:
        name (str): name of the GPU kernel.
    Returns:
        A boolean indicating if the kernel is a computation kernel.
    """
    return not NCCL_COMPUTE_KERNEL_RE.match(name)

eg：cudaMemsetsync will be considered as the compute kernel

**Comment by zwj0117** [comment]
I don't know why the“ .* ”I copied into the issue disappeared
